### ISSUE TITLE
[checklist] Problem with rendering `slds-checklist` component in Angular app

### ISSUE THREAD

**Issue by anna-lach** [sl-design-system/components#1106]
We were trying to add the `<slds-checklist>` component to our Angular demo app: https://github.com/sl-design-system/angular-demo/commit/6a50875b23fe0437c6a89880fab0261e9d273eeb
but the component is not rendering, there is no shadow DOM

<img width="881" alt="image" src="https://github.com/sl-design-system/components/assets/111562742/251750c9-5e46-4782-8b66-6ad8068d368f">

Maybe some exports are missing? We need to investigate.

**Comment by jpzwarte** [comment]
Fixed in https://github.com/sl-design-system/angular-demo/pull/5
