### ISSUE TITLE
[Contextual Menu] Documentation

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1138]
```[tasklist]
### Tasks
- [x] UX Dcoumentation
- [x] Code documentation
- [x] A11y documentation
- [x] add related components
```

**Comment by anna-lach** [comment]
Dev part of documentation is added, we need to wait for the component in Figma.

**Comment by anna-lach** [comment]
Probably there will be some changes to the documentation needed after discussion about single and multi select variants in the menu #1427
