### ISSUE TITLE
Change the color for badge component - 'info' state

### ISSUE THREAD

**Issue by Martrybus** [sl-design-system/components#1284]
### Provide a general summary of the issue here

Hello, I'd like to change the color for the badge component - '**Info'** state. We need a ligher color.

### 🤔 Expected Behavior?

Currently, the color for the Info state of the badge component is #175D79. It is too dark, we need it to be in line with the other info/accent colors in the application. The color that we prefer is #4589BE (color.palette.info.500) - it is our default color for accents and info states.

### 😯 Current Behavior

![badge color](https://github.com/sl-design-system/components/assets/170721457/a76732fd-d803-4a9f-8f33-56fa2ac17571)

### 🎨 Your Theme(s)

Editorial Suite

**Comment by DanielleRameau** [comment]
Hi Maria, we did choose for the darker shade due to color contrast issues: 

![Image](https://github.com/sl-design-system/components/assets/111998351/39521b1b-7747-4ef9-8f57-43e74f927087)

**Comment by DanielleRameau** [comment]
We leave it as is due to color contrast issues.
