### ISSUE TITLE
Support for FA animated icons

### ISSUE THREAD

**Issue by adamPrzybyszExt** [sl-design-system/components#1288]
### Provide a general summary of the feature here

Support for FA animated icons like here: https://docs.fontawesome.com/web/style/animate

### 🤔 Expected Behavior?

It is possible to make the FA icon animated

### 😯 Current Behavior

No possibility to make icons animated

### 🔦 Context

We (ETSL) currently use animated icon inside button e.g. when Logging in action is in progress (spinner).

### 🧢 Your Product/Team

ETSL

**Comment by DanielleRameau** [comment]
@adamPrzybyszExt do you need animated icons for this? We have a spinner component available: https://storybook.sanomalearning.design/?path=/story/components-spinner--all Does this suit your needs?

**Comment by DanielleRameau** [comment]
We are closing this issue for now. If a specific use case pops up we will look into it again.
