### ISSUE TITLE
Cleaning up unused themes

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1327]
There are a lot of unused themes available in the library without tokens, let's clean the library and only add a theme when it exists, don't place it there for future purposes.
```[tasklist]
### Themes that can be removed
- [x] Bingel DC dark
- [x] Bingel INT dark
- [x] Bingel as a whole
- [x] clickedu dark
- [x] itslearning dark
- [x] Nowa Era as a whole
- [x] kampus dark
- [ ] share clean up in slack channel and sprint review with explanation
- [x] designer cleans it up in figma
- [ ] developer will change the rest
- [ ] utbildning and myvanin are on hold, remove from storybook dropdown
```

**Comment by Diaan** [comment]
I changed the folder name `myvanin (onhold)` to `myvanin_onhold` because spaces aren't always a good idea in folder names. Same for the utbildning one.
I think I changed it everywhere, but a double check in figma couldn't hurt.
