### ISSUE TITLE
Bug in the prototype behaviour of search field

### ISSUE THREAD

**Issue by Martrybus** [sl-design-system/components#1361]
### Provide a general summary of the issue here

Hi, when I use the search field in my prototypes (size **large**), it changes the size to **md** when I hover the field or click on it.

### 🤔 Expected Behavior?

When you click or hover the search field in a prototype, it does not change its size from large to md.

### 😯 Current Behavior

https://github.com/sl-design-system/components/assets/170721457/3ec9a54d-719a-41e7-8327-71eb8321d3ab

### 📎 Link to Figma

https://www.figma.com/proto/S5QgDy8X9eqhvECPANSZMM/Editorial-Suite-designs?page-id=5287%3A28538&node-id=6539-97155&viewport=558%2C3395%2C0.25&t=rAu0z0d3ihCFpNwg-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=6539%3A97155

### 🎨 Your Theme(s)

Editorial Suite

**Comment by DanielleRameau** [comment]
@Martrybus Hi Maria, I want to fix the search field hover state but can't reproduce it in the SLDS file. I only see the link to the prototype in the issue, could you also share the Figma link? Then I can have a closer look, thanks.

**Comment by DanielleRameau** [comment]
solution: Ensure the placeholder property is always enabled when no value is provided.
