### ISSUE TITLE
Slow FA icon load in sl-icon

### ISSUE THREAD

**Issue by adamPrzybyszExt** [sl-design-system/components#1366]
### Provide a general summary of the issue here

When there are several FA sl-icons then these icons are loaded after 1-2 seconds which looks preety bad.

### 🤔 Expected Behavior?

FA icons should be loaded immedately.

### 😯 Current Behavior

FA icons are visible after some perod of time.

### 🖥️ Steps to Reproduce

https://github.com/sl-design-system/components/assets/101642279/7003fc33-c839-4e53-b265-6b817fcc0453

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### What operating system are you using?

Windows 10

### 🧢 Your product/team

ETSL

### 🎨 Your Theme(s)

Editorial Suite

**Comment by adamPrzybyszExt** [comment]
I register icons once, only on  app init
`Icon.register(
      faArrowRotateLeft,
      faArrowTurnDownRight,
      faArrowUpRightFromSquare,
      faAt,
      faBookCircleArrowUp,
      faCaretDown,
      faCaretUp,
      faCheck,
      faChevronDown,
      faChevronLeft,
      faChevronRight,
      faChevronsLeft,
      faChevronsRight,
      faChevronUp,
      faCircleInfo,
      faClock,
      faDownload,
      faEllipsisVertical,
      faEye,
      faEyeSlash,
      faFileMagnifyingGlass,
      faFolder,
      faFolderClosed,
      faFolderGear,
      faFolderGrid,
      faGripDotsVertical,
      faImage,
      faLayerPlus,
      faLock,
      faMagnifyingGlass,
      faMagnifyingGlassPlus,
      faPencil,
      faPlus,
      faRectangleList,
      faRotate,
      faSignalStream,
      faTrash,
      faTriangleExclamation,
      faUser,
      faXmark,
    );`
    
    Problem occurs on button/icon load e.g. route change. 
    
    I removed most of the icons wfrom register method, left only 2 - it still loads slowly. That looks like loading registered icons itself(based on `name` attribute) becomes slow when there is more icons to load at the same time.

**Comment by Diaan** [comment]
@adamPrzybyszExt In my little test setup I've added all 1959 icons from the free solid collection and the icons still load nearly instantly. So theoretically the 40 you are using shouldn't be a problem during the load of the actual icon.

Icons are stored in `window.SLDS.icons`; could you make a screenshot of the value it has before you click the "advanced search" button, and one after it? Does it change?
And when does this file (and ones similar) get loaded?
![Image](https://github.com/user-attachments/assets/82b90bf9-d57d-4472-b8ca-fe6c9efd3fee)

**Comment by adamPrzybyszExt** [comment]
Can you try add more icons to html? And also icons inside `sl-button`.

Window object doesn't change
![image](https://github.com/user-attachments/assets/442acb71-b938-4b8d-b774-3c775d86e7d4)

All needed scripts are included in big vendor.js file which is available from the start.

**Comment by Diaan** [comment]
That is interesting :D I'm going to use this to try to reproduce it and see if it's something we can improve.

**Comment by adamPrzybyszExt** [comment]
Didn't saw you question :) not really, we use angular binding in many places to dynamically show an icon
