### ISSUE TITLE
[Data grid] [Behaviour] Delete Content

### ISSUE THREAD

**Issue by arecuenco-dsgn** [sl-design-system/components#1385]
## Introduction
When you delete a row in a data grid, the system might show a warning message. This message ensures you want to delete the item so you don't accidentally lose important data. It's a way to confirm your decision before the deletion happens.

```[tasklist]
### Tasks
- [ ] [Data Grid] UI of the Delete Content
- [ ] [Data Grid] Development of the Delete Content
```

**Comment by DanielleRameau** [comment]
This should be handled on the side of the CFA and not the design system; we have a message dialog available for this use case.
