### ISSUE TITLE
Add Search functionality to Select Component

### ISSUE THREAD

**Issue by mathiascasapouso** [sl-design-system/components#1394]
### Provide a general summary of the feature here

We would like to have a search box on the Select Component to filter the available options.

### 🤔 Expected Behavior?

There is a search box on the first position of the options within the ¨listbox¨ part. This searchbox filters the available option on input. Has the look and feel of the selected theme. This search box can be enabled via a optional property

### 😯 Current Behavior

There is no search functionality available

### 💁 Possible Solution

Reuse the new Search Field component

### 🔦 Context

We have a form where a Author needs to select a Learning Goal from all the Learning Goals available, this can be tricky as there are 512 avaialble atm.

### 🧢 Your Product/Team

BTM/Avengers

**Comment by jpzwarte** [comment]
@mathiascasapouso What you're describing is probably the combobox component, which we are developing. See #258

**Comment by mathiascasapouso** [comment]
That is geat news @jpzwarte . I think this issue can be closed then. I'll wait for the Combobox Component, is there a estimated date for the release?

**Comment by jpzwarte** [comment]
There is no ETA yet. I think the best way to keep track of the progress is to monitor #258 and related tasks.
