### ISSUE TITLE
[Badge] Padding in Figma component is much smaller than in Web component

### ISSUE THREAD

**Issue by jtalen** [sl-design-system/components#1415]
### Provide a general summary of the issue here

Padding of the Badge component in Figma is much smaller than in Web component on your documentation website:
https://sanomalearning.design/categories/components/badge/

### 🤔 Expected Behavior?

There should be enough padding left and right to have a visually balanced component. Like on your documentation website

### 😯 Current Behavior

The padding in the badge is only 3px instead of 8px used on the documentation website.

<img width="234" alt="image" src="https://github.com/user-attachments/assets/edeef39d-a1fe-4a86-b787-34fe1c134af6">

FA icon: puzzle

### 💁 Possible Solution

Change the padding in Figma to 8px instead of 3px.

### 📷 Screenshots

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/b914765b-cca4-4ff0-b6d4-3d103ab811e6">

### 🎨 Your Theme(s)

Magister

**Comment by DanielleRameau** [comment]
old badge should be on deprecated (publish as hidden) and publish the new badge

**Comment by DanielleRameau** [comment]
@jtalen  is testing the new badge component and will leave his input in this issue

**Comment by jtalen** [comment]
- In the MD badge de text isn't vertically centered. This is due to the baseline of the Open Sans font. Figma has a setting to trim the vertical height called: 'Cap height to Baseline'. This ensures there isn't any whitespace in the text, so it can be vertically centered. 

First badge is with the setting 'Cap height to Baseline'
![image](https://github.com/user-attachments/assets/9b974910-6add-4670-93e8-1cb3ba29e764)

https://github.com/user-attachments/assets/45d4c4a9-995b-4644-a79c-4bce52e6a7b5

- Primary and info are exactly the same, maybe they should be different?
