### ISSUE TITLE
accordion doesn't open correctly with an expression

### ISSUE THREAD

**Issue by fransdeboer** [sl-design-system/components#1418]
### Provide a general summary of the issue here

Opening an accordion item under a certain condition doesn't work correctly. Given the code below, the accordion item is always open, regardless of the result of the function isSuccess. When toggling the item (with the mouse) the accordion item doesn't respond after one or mouse clicks 

```
<sl-accordion-item .summary=${this.gradePeriod} ?open=${!this.#isSuccess()}>

  #isSuccess(): boolean {
    return this.response?.every(r => r.status !== CreateColumnStatus.error) ?? true;
  }
```

### 🤔 Expected Behavior?

the accordion item should open or not open, depending on the result of the function (true / false)

### 😯 Current Behavior

see the description above

### 🖥️ Steps to Reproduce

fill the `.open` attribute with an dynamic value (expression) and click multiple times on the accordion to open and close it

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### What operating system are you using?

WSL

### 🧢 Your product/team

Magister

### 🎨 Your Theme(s)

Magister

**Comment by DanielleRameau** [comment]
@jpzwarte contact @fransdeboer

**Comment by jpzwarte** [comment]
Closing this as the bug is being tracked in #1420
