### ISSUE TITLE
[Accordion] You cannot change the open state of an accordion item using the `open` property

### ISSUE THREAD

**Issue by jpzwarte** [sl-design-system/components#1420]
### Provide a general summary of the issue here

A user used the `open` property to change the open/closed state of the accordion. This did not work, since the component only checks the `open` property on initial render. Instead the user needed to use the `toggle()` method.

Extracted from #1418 

### 🤔 Expected Behavior?

This "mistake" is probably not the last time we see this. Consider changing accordion-item to also work given the above usecase.

### 😯 Current Behavior

-

### 🖥️ Steps to Reproduce

-

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### What operating system are you using?

macOS

### 🧢 Your product/team

SLDS

### 🎨 Your Theme(s)

Sanoma Learning

**Comment by Diaan** [comment]
The problem seems to be with `?open=state`, this doesn't work with the removing of the attribute in the component.
In angular with `[open]="state"` it does work
