### ISSUE TITLE
[menu button] remove "single" and "multiple" select variants

### ISSUE THREAD

**Issue by Diaan** [sl-design-system/components#1427]
in storybook there are "single" and "multiple" select stories. This is not an option in Figma (yet) we don't really know what the use case for these is, how it differs from a regular select / combobox.
We need to have some background info such as use cases/ usages/ patterns to be able to write proper documentation if we actually need those variants.
https://storybook.sanomalearning.design/?path=/story/components-menu-button--single-select
https://storybook.sanomalearning.design/?path=/story/components-menu-button--multi-select
```[tasklist]
### Tasks
- [x] Discuss
- [ ] remove multi and single select property menu button
- [ ] Review documentation, is there anything to update?
```

**Comment by DanielleRameau** [comment]
Remove properties for now, we need to work on a pattern in a later stage (see #1466 )
