### ISSUE TITLE
[Button Bar] Set standard variants

### ISSUE THREAD

**Issue by jtalen** [sl-design-system/components#1437]
### Provide a general summary of the issue here

In the sizes MD and LG some of the buttons have the wrong font family.

<img width="756" alt="image" src="https://github.com/user-attachments/assets/d7f22e44-4737-45a5-b71e-72ca7a5cc7a6">

![image](https://github.com/user-attachments/assets/3ce09624-bbed-493b-8162-45957fb745ed)

### 🤔 Expected Behavior?

All buttons should be the same, because it should be the same component. But half of all the buttons have the wrong font family. It should be 'Open Sans'

### 😯 Current Behavior

2 of 4 buttons MD and LG are 'Source Sans Pro'.

### 💁 Possible Solution

Use the same button component for all buttons in the button bar. And don't overwrite them...

### 📎 Link to Figma

https://www.figma.com/design/YZeBneflpJkX3KXSyvMrqP/Magister-Light-mode?m=auto&node-id=1919-103221&t=yLgn0JmjguMWTG8T-1

### 🎨 Your Theme(s)

Magister
```[tasklist]
### Tasks
- [x] Apply tokens again and check all variants.
- [ ] Set standard variants within the themes.
```

**Comment by DanielleRameau** [comment]
I did a quick fix to help Magister out.
In the theme, we implemented the most common magister bar so they don't have to change the buttons inside.

**Current issue:**

When you change the button variant after inserting the content the content will be lost after switching the variant. To solve this we need to set standard variants within the themes.
