### ISSUE TITLE
[Select] Manual resize (horizontally) not possible

### ISSUE THREAD

**Issue by jtalen** [sl-design-system/components#1438]
### Provide a general summary of the issue here

Resize a selectbox manually isn't possible

![image](https://github.com/user-attachments/assets/878fec7a-df88-4bb5-832c-32ea8d1b8e59)

### 🤔 Expected Behavior?

That the selectbox should be set to fill and when you resize this component it will be as wide as you want it to be.

### 😯 Current Behavior

![image](https://github.com/user-attachments/assets/6d0345c8-294d-4ee5-ae8d-d0c024e242f0)

### 💁 Possible Solution

Let the actual selectbox fill the available space.
![image](https://github.com/user-attachments/assets/2e478c11-f93e-4f0b-80a0-f8498bb4dbfb)

### 🎨 Your Theme(s)

Magister

**Comment by RoaldBoerema** [comment]
I fixed this in Magister Light theme (Jeremy needed the component)
