### ISSUE TITLE
Finetuning tag

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1465]
```[tasklist]
### Tasks
- [ ] update active tokens, make it a bit darker then hover
- [x] change `aria-label` of the remove button from `Remove` to `Remove <tag label>`
```

**Comment by anna-lach** [comment]
To discuss:

Right now, the whole tag is focusable and a button inside is not focusable. According to Anna Karoń suggestions, the `remove button` should be also focusable and when we focus it we should be able to remove the `tag` by using `Space` or `Enter` with keyboard (just like clicking button works), not like it's working right now – focusing the whole `tag` and removing it with `Backspace` or `Delete`. It should be more intuitive for the users.

**Comment by jpzwarte** [comment]
This has already been done in #1457
