### ISSUE TITLE
[tag] Update active state of tags to reflect latest components

### ISSUE THREAD

**Issue by jpzwarte** [sl-design-system/components#1475]
### Provide a general summary of the issue here

After some insight, we changed that active state to be less "dramatic" in the tab components. The Figma designs need to be updated to match that.

### 🤔 Expected Behavior?

The focused subtle state now just has the focusring with the idle subtle background colors. Same for the bold focused state.

### 😯 Current Behavior

- 

### 🎨 Your Theme(s)

Sanoma Learning

**Comment by DanielleRameau** [comment]
will be done with implementing contextual tokens
