### ISSUE TITLE
Build in github actions produces different css from local build

### ISSUE THREAD

**Issue by Diaan** [sl-design-system/components#1478]
### Provide a general summary of the issue here

There seems to be a difference between the tokens generated when running locally to when run on github actions:
![image](https://github.com/user-attachments/assets/d6701728-2a24-4923-ad08-8665ab8d963c)
![image](https://github.com/user-attachments/assets/ed692aa8-620f-4f36-90d8-d31e73b4be74)
On github actions the `calc()` function is missing, while both use the exact same code for the tokens

### 🤔 Expected Behavior?

both build should have the same outcome

### 😯 Current Behavior

difference in the generated css

### 🖥️ Steps to Reproduce

create a PR and check components that use `calc` in a token. In this case a toggle button in the clickedu theme

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### What operating system are you using?

Mac

### 🧢 Your product/team

SLDS

### 🎨 Your Theme(s)

Sanoma Learning

**Comment by DanielleRameau** [comment]
solved in #1480
