### ISSUE TITLE
FA icon disappears / changes to text inside button component

### ISSUE THREAD

**Issue by vv0zny** [sl-design-system/components#1482]
### Provide a general summary of the issue here

FA icon disappears / changes to text inside button component.

### 🤔 Expected Behavior?

When I hover on the button or just load the page in Prototype mode, the icon inside the button should remain always the same (visible and not in text format)

### 😯 Current Behavior

FA icon disappears / changes to text inside button component.

### 💁 Possible Solution

Figure out why FA icons behave like that inside components. Is it some Figma bug or the way components are built / FA is used?

### 📷 Screenshots

![image](https://github.com/user-attachments/assets/9c188695-ea23-4988-b80c-bceb19393d9a)
![image](https://github.com/user-attachments/assets/28358930-db1a-4b35-ac1e-4eb7d70a1dd6)

### 🎨 Your Theme(s)

Bingel INT

**Comment by RoaldBoerema** [comment]
Can't reproduce. Looks like a Figma update fixed the issue.
@vv0zny Could you check if the issue still persist on your end?

**Comment by DanielleRameau** [comment]
@vv0zny Hi Karol, we are currently refactoring our components to the new design token setup and this issue will be solved in that update. Please let us know if you have any further questions.
