### ISSUE TITLE
[toggle-group] Focus outline is clipped

### ISSUE THREAD

**Issue by jpzwarte** [sl-design-system/components#1532]
### Provide a general summary of the issue here

![CleanShot 2024-09-19 at 10 21 04@2x](https://github.com/user-attachments/assets/f112f040-b1e2-4c1d-9255-e7b5be25e81b)

### 🤔 Expected Behavior?

It should not clip the focus outline.

### 😯 Current Behavior

- 

### 🖥️ Steps to Reproduce

https://storybook.sanomalearning.design/?path=/story/actions-toggle-group--all

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### What operating system are you using?

macOS

### 👤 Your name

Jeroen Zwartepoorte

### 🧢 Your product/team

SLDS

### 🎨 Your Theme(s)

Sanoma Learning

**Comment by DanielleRameau** [comment]
solved in #1163
