### ISSUE TITLE
[THEMING] Token for 'details' background for use in our components..

### ISSUE THREAD

**Issue by rvanderveen058** [sl-design-system/components#1581]
### Provide a general summary of the feature here

For several backgrounds of our components we use a calculated color from our old dna style.. 

We would like to use a SL-DS token instead.. --sl-color-palette-primary-25 to be precise.. 
But because of dark-mode... we don't want to use a primary color for this. 

Therefore I would like to request for some sort of 'details'-background token like --sl-background but with in our case a slightly more blue.. --sl-color-palette-primary-25 in light and to be determined counter color for dark mode..
  

### 🤔 Expected Behavior?

Just an extra token..

### 😯 Current Behavior

Lack of token...

### 🔦 Context

As a developer we would like to easily use the same background color throughout different parts of our application...

### 👤 Your name

Ronald van der Veen

### 🧢 Your Product/Team

Magister

**Comment by DanielleRameau** [comment]
@rvanderveen058 after a discussion with Jurrit we decided to call this token 'body.background'. In our new token setup (contextual token project) which we are working this token will be called 'elevation.surface' which means this color will be the basic background within the UI of Magister. The primary.50 token will be used as default hover color.
