### ISSUE TITLE
Button tokens in Clickedu theme

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#165]
|<div align="left">**What is the problem we are solving and why?**|
|-------------|
|As a user, I want to have accessible and a consistent buttons, so I can perform my actions quickly| 
|As a developer, I want to have an easy to use button component, so I can quickly implement actions in the user interface of the product|
|As a designer, I want to have clear UX documentation and an easy to use Figma component of a button, so I can quickly create actions in my prototypes| 

## Description
The button component needs tokens for the Clickedu theme.

## Design
Ask development team where we can find the current buttons of Clickedu.

https://github.com/sanomalearning/design-system/issues/165#tasklist-block-66dff538-4b0b-4fff-ba83-b6f8f8fb9d0b

**Comment by Diaan** [comment]
Is fixed in #471
