### ISSUE TITLE
[DATA-SOURCE] is missing a declaration file

### ISSUE THREAD

**Issue by fransdeboer** [sl-design-system/components#1678]
### Provide a general summary of the issue here

When using the the data-source package (import { ArrayDataSource } from '@sl-design-system/data-source';) TypeScript shows an error that the declaration file is missing

![image](https://github.com/user-attachments/assets/804ded35-5cbe-440f-9bb7-aa1ce84d3cea)

### 🤔 Expected Behavior?

-

### 😯 Current Behavior

-

### 💁 Possible Solution

Please add a index.d.ts file 

### 🖥️ Steps to Reproduce

add version 0.0.1 with  `npm add @sl-design-system/data-source` to a project, and import the library

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### What operating system are you using?

Windows 

### 👤 Your name

Frans de Boer

### 🧢 Your product/team

Magister

### 🎨 Your Theme(s)

Magister

**Comment by DanielleRameau** [comment]
@fransdeboer This bus will be fixed in the next release!
