### ISSUE TITLE
Create UI of text field in default theme

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#197]
## Description
The SL Design System needs a input field component. This task is created to design the UI design of the input field in the default theme.

## Design
Create a UI design of the input field in all types and states based on the first draft of the UX documentation. See issue #196 
In this design we used the SL button component.

**Types**
- text
- email
- tel
- url
- number

**Requirements**
- available in different sizes
- labels
- validation
- support prefix and or suffix
- help text

States
- idle
- hover
- focus
- active
- disabled
- invalid
- valid
- read-only

```[tasklist]
### Tasks
- [ ] lightmode (all states)
- [ ] darkmode (all states)
```

**Comment by Diaan** [comment]
Light Theme:
https://www.figma.com/file/1oIVcD9VMbOtLXYp48ehsA/SL-Light-mode?node-id=2180-7430
Dark Theme:
https://www.figma.com/file/gnrOGCDlfN2c8HnPk12g6w/SL-Dark-mode?node-id=1208-4660
