### ISSUE TITLE
Create UI of switch component in default theme

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#220]
## Description
The switch component is part of the MVP of the SL Design System. A toggle switch is a digital on/off switch. Toggle switches are used for changing the state of system functionalities and preferences.

```[tasklist]
## Tasks
- [x] lightmode/darkmode
- [x] help text
- [x] different states
- [x] custom size labels
- [x] vertical layout
```

## UX Patterns
https://www.nngroup.com/articles/toggle-switch-guidelines/

## Design
Create a UI design of the switch in all types and states based on the first draft of the UX documentation. See issue #219.

https://gui-challenges.web.app/switch/dist/ (left side, not vertical)

**Comment by Diaan** [comment]
Some inspiration:
https://web.dev/building-a-switch-component/

https://gui-challenges.web.app/switch/dist/
I think we should focus on the left column in the MVP, the rest is optional (apart from maybe the sizing)

**Comment by DanielleRameau** [comment]
@RoaldBoerema can you review this?
