### ISSUE TITLE
Development of switch component

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#223]
## Description
The switch component is part of the MVP of the SL Design System. A toggle switch is a digital on/off switch. Toggle switches are used for changing the state of system functionalities and preferences.

```[tasklist]
### Acceptence criteria
- [x] keyboard nav
- [x] default state
- [x] focus state
- [x] disabled state
- [x] disabled checked
- [x] icons in the thumb; default an x and a v, but should be configurable
- [ ] vertical layout
- [ ] cutom sized labels
```
## examples
https://web.dev/building-a-switch-component/
https://gui-challenges.web.app/switch/dist/

## Design
See issue #220 
base component:
https://www.figma.com/file/SKFTFiiz7YK9E2TPfCan9o/Base-Components?type=design&node-id=1215-5016&t=2jHZV2tSrJ3EaE8U-0
in SL light theme: 
https://www.figma.com/file/1oIVcD9VMbOtLXYp48ehsA/Sanoma-Learning-Light-mode?node-id=2180-7430

**Comment by jpzwarte** [comment]
https://web.dev/building-a-switch-component/

**Comment by Diaan** [comment]
Put on hold for now until we figure out the issue with the sizing of the labels; should they match with the size of the toggle or should they be left up to the user (like they are now for all other inputs).
If they are flexible; how is the alignment going to be?

**Comment by arecuenco-dsgn** [comment]
Waiting till the new vertical layout is added to Figma:
 #220

**Comment by Diaan** [comment]
to do:
- make sure `no-label` also gets added on load, not just on slot change.
