### ISSUE TITLE
Demo application to test npm packages

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#244]
Create a web application *outside* of the `design-system` repository that uses the `@sanomalearning/slds-core` etc. packages as an actual user of the SLDS would. That way we can make sure that the NPM packages we release are ready for use. We can also validate the DX of the packages & components.

This application *could* eventually become a sort of "reference implementation" for the SLDS.

```[tasklist]
### Tasks
- [ ]Publish SL theme npm package
- [x] Publish SL theme package
```

**Comment by DanielleRameau** [comment]
@jpzwarte can write this story please?

**Comment by jpzwarte** [comment]
@DanielleRameau done
