### ISSUE TITLE
Development of dialog

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#275]
```[tasklist]
### Acceptance criteria
- [x] Dialog should be accessible
- [x] A title in header
- [x] It is possible to insert any content that you want
- [ ] Space for multiple buttons on the left side and on the right side
- [x] Block scrolling in the background
- [x] Disable esc or clicking outside of dialog
- [x] It should be possible to add a button in the top right corner of the doalog for example to close the dialog
- [x] Transparent overlay/background/backdrop
- [x] Header and buttons and are sticky when there is too much content, content is scrollable
- [x] Mobile behavior (slide from the bottom to top)
- [ ] Header is placed in flex block: flex-direction column/column-reverse (in tokens)
```

**Comment by anna-lach** [comment]
For now we cannot use our token in the right way for the backdrop background, because `::backdrop` does not inherit from `:root`, this is a bug that will be fixed in the future: https://drafts.csswg.org/css-position-4/#backdrop

We will leave a kind of workaround for now that needs to be changed later.

**Comment by DanielleRameau** [comment]
Title reversed is a theme setting and should not be a property per instance. The property should change the whole theme setting. Header is placed in flex block: flex-direction column/column-reverse (in tokens)

**Comment by anna-lach** [comment]
Footer flex-direction and justify-content will be a property (token) per theme. When there will be two buttons in the footer we will use slotted `sl-button-bar`, when there will be more buttons than two, the developer will be able to use his/her own `sl-button-bar` inside.
We will have one sl-button-bar gap per theme (in general).
