### ISSUE TITLE
[V1] Inline Message

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#277]
## User Story
As a Sanoma Learning Design System user, I want a versatile and user-friendly Inline Message Component that can effectively handle various use cases across our educational products. This Inline Message Component should be adaptable to convey:

## Definition
Inline messages are strategically positioned cues in user interfaces, providing contextual information and notifying users of ongoing actions. Displaying updates or warnings related to system aspects, ensuring users are promptly informed of necessary changes for a seamless experience.

## Key Points
- Appear near their related items.
- Fill the width of the container.
- Does not dismiss automatically.
- Do use to inform the user about ongoing events in flow.
- Do use for confirmation and low-priority messages.

## Acceptance Criteria

**Elements**
- Icon
- Title
- Description
  - Plain text
  - Summary List (Error list)
- Close Button

**Status**
The status defines how the design system visually displays the components inside of the message. **For example, a warning message with an inline link would automatically use the warning link variant.** Not possible to do this within the component, explain in documentation.
- Info (Default)
- Success
- Warning
- Danger

**Sizes** 
For version 1, we only focus on one size. It’s important to remember that the content area must define the width of the Inline Message.
- Medium (Default)

**Position**
The inline message must be positioned close to the workflow area and needs to be visible when it appears. In a form, the message will appear inline at the bottom of the form, close to the submit button. In a table view, the messages will appear at the top of the page to make it more visible the first time.
- Inline Top
- Inline Botton

**A11y**
- Screen readers will announce the text inside the Inline Message without moving the focus to the Inline Message.
- Using an Inline Message for long messages because they aren’t timed, making it easier for people with various disabilities to get the entire message.

**Tokens Notes**
- Left Border - Some products have a much thicker border.

## Figma Links
- [Figma Inline Message Component Research](https://www.figma.com/file/PGb66fVN325tu0IngRka66/Component-Research?type=design&node-id=52-422&mode=design&t=zM963NoDdSV01FB0-4)

## Reference Links
- [How to make inline error messages accessible](https://hidde.blog/how-to-make-inline-error-messages-accessible/), by Hidde de Vries
- [Code Library of Accessibility](https://dequeuniversity.com/library/aria/alert#:~:text=An%20alert%20is%20a%20special,them%20obvious%20when%20they%20appear.)

```[tasklist]
### User stories
- [ ] https://github.com/sl-design-system/components/issues/636
- [ ] https://github.com/sl-design-system/components/issues/717
- [ ] https://github.com/sl-design-system/components/issues/607
- [ ] https://github.com/sl-design-system/components/issues/608
- [ ] https://github.com/sl-design-system/components/issues/609
- [ ] https://github.com/sl-design-system/components/issues/850
```

**Comment by DanielleRameau** [comment]
@arecuenco-dsgn One question I still have after our Alert discussion; if you use for example a warning alert with an inline link, will it automatically use the warning link styling? This makes it easier for developers to implement the correct styling.

**Comment by arecuenco-dsgn** [comment]
We decided to update the name of components from "Alert" to "Inline Message". Change it, we avoid the conflict with the pattern and focus more on the type of notification.

**Comment by anna-lach** [comment]
We've decided to use `variant` instead of `status`.
