### ISSUE TITLE
[V1] Skeleton

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#280]
## User Story

As a member of the design and development team responsible for our Design System, I want to introduce a Skeleton Loading State component to enhance the user experience when content is loading or being fetched. This component should follow our established design principles and be easily integrated into our Design System, ensuring consistency across our products and applications.

## Acceptance Criteria

1. **Skeleton Loading Component Creation:**
   - Create a reusable Skeleton Loading State component that can be easily integrated into various parts of our Design System.

2. **Customization Options:**
   - Implement customization options for the Skeleton Loading State, allowing developers to adjust its appearance, size, and animation to align with specific use cases and design needs.

3. **Design System Integration:**
   - Ensure seamless integration of the Skeleton Loading State into our Design System, adhering to our design guidelines, typography, color schemes, and spacing.

4. **Accessibility Considerations:**
   - Implement accessibility features, including appropriate ARIA attributes and roles, to make the Skeleton Loading State accessible to users with disabilities and in line with accessibility best practices.

5. **Responsive Design:**
   - Design the Skeleton Loading State to be responsive and adaptable to various screen sizes and devices, maintaining readability and usability.

6. **Animation and Transitions:**
   - Incorporate subtle and smooth animations and transitions to enhance the user experience while the skeleton content is displayed. Ensure that animations do not distract or impede usability.

7. **Documentation and Usage Guidelines:**
   - Create comprehensive documentation for the Skeleton Loading State component, including usage guidelines, code examples, and best practices. Ensure that developers can easily understand and implement it.

8. **Cross-Browser Compatibility:**
   - Thoroughly test the Skeleton Loading State component across multiple browsers (e.g., Chrome, Firefox, Safari, Edge) and devices to ensure consistent behavior and cross-browser compatibility.

9. **Performance Optimization:**
   - Optimize the performance of the Skeleton Loading State component to ensure that it loads quickly and efficiently, contributing to a smooth user experience.

10. **Feedback Mechanism:**
    - Establish a feedback mechanism or channel for developers and designers to provide input, report issues, and suggest improvements for the Skeleton Loading State component.

## Definition of Done

- The Skeleton Loading State component is successfully created and integrated into our Design System.
- Customization options are available to tailor the Skeleton Loading State's appearance and behavior to different use cases.
- Comprehensive documentation, including usage guidelines and code examples, is provided for developers.
- Testing and validation have been performed to ensure cross-browser compatibility and accessibility compliance.
- The Skeleton Loading State is optimized for performance and aligns with our established design principles.

## Additional Notes

Implementing a Skeleton Loading State component in our Design System will improve the user experience by providing visual feedback during content loading, reducing perceived load times, and maintaining design consistency across our products and applications. This component will be a valuable addition to our Design System toolkit.

```[tasklist]
### User stories
- [ ] https://github.com/sl-design-system/components/issues/530
- [ ] https://github.com/sl-design-system/components/issues/618
- [ ] https://github.com/sl-design-system/components/issues/619
- [ ] https://github.com/sl-design-system/components/issues/858
```

**Comment by arecuenco-dsgn** [comment]
@RoaldBoerema Will have a look over tokens.
