### ISSUE TITLE
Development of popover

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#285]
```[tasklist]
### Acceptance criteria
- [x] open on click
- [x] dynamic alignement pointer (define dafault and fall back top, left, right and bottom)
- [x] define start and end of pointer (left, center, right)
- [x] button has active state popover is open
- [x] content of popover can be defined by development team (more then just text)
- [ ] fall back for firefox
```

**Comment by anna-lach** [comment]
With current polyfill changes (styles added in polyfill's `popover.ts` file) the popover (and a tooltip) is not working properly in Firefox, we cannot overwrite styling added in the polyfill: https://github.com/oddbird/popover-polyfill/issues/147

**Comment by anna-lach** [comment]
TODO (what's left):
- improve a11y
- `delegatesFocus` bug in Firefox
- fix closing popover on escape in Firefox
- unit tests

**Comment by anna-lach** [comment]
Waiting for input:
https://github.com/oddbird/popover-polyfill/issues/147
https://github.com/oddbird/popover-polyfill/issues/154
