### ISSUE TITLE
Design of tooltip

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#287]
Discuss acceptance criteria

```[tasklist]
### Tasks
- [x] Tooltip SL dark mode
- [x] Tooltip SL light mode
```

**Comment by RoaldBoerema** [comment]
[Base component](https://www.figma.com/file/SKFTFiiz7YK9E2TPfCan9o/Base-Components?type=design&node-id=2611%3A18498&mode=design&t=6d0LRVRPNYHRWzqW-1) 
[SL light](https://www.figma.com/file/1oIVcD9VMbOtLXYp48ehsA/Sanoma-Learning-Light-mode?type=design&node-id=4167%3A24693&mode=design&t=VQRQF31JzUHdZQHQ-1)
[SL dark](https://www.figma.com/file/gnrOGCDlfN2c8HnPk12g6w/Sanoma-Learning-Dark-mode?type=design&node-id=1523%3A9733&mode=design&t=CKqaghDLIU5PNn50-1)
