### ISSUE TITLE
UI of avatar

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#290]
Discuss acceptance criteria

```[tasklist]
### Acceptance criteria
- [x] sizes: "s" | "m" | "l" | "xl" | "xxl" | "xxxl" (default: M)
- [x] name and sub heading on the right side of avatar
- [x] add online/offline status
- [x] fall back option: initials and custom icon
- [x] shapes: rounded and rectangle (product had to choose 1, no mix); token for border-radius; when set to 0; square, when set to 50%; round
- [x] Add a placeholder for badge (notifications)
```

**Comment by Diaan** [comment]
How should A11y work for this component? 
Does the image always have an alt-text, or only when the name is hidden?
Should the initials (which are an svg) have alt-text?

**Comment by DanielleRameau** [comment]
Good question! This is what I found after some research:

1. **Alt-Text for the Image:** Always provide an alt attribute for the avatar image, describing its content or purpose. 
2. **Alt-Text When Name is Hidden:** Even if the user's name is visually hidden, ensure the alt text for the image conveys meaningful information.
3. **Alt-Text for Initials (SVG):** If using SVG initials as a fallback, give them an aria-label attribute with the user's name or a description.

This ensures accessibility for users, including those relying on screen readers or with images disabled.

**Comment by DanielleRameau** [comment]
Can we ask a specialist? Or someone that uses a screenreader?
