### ISSUE TITLE
Fix core tokens values - textDecoration and letterSpacing

### ISSUE THREAD

**Issue by anna-lach** [sl-design-system/components#314]
**Describe the bug**
We have some values in core tokens that will not work correctly in css.

For the text decoration we have a value like `strikethrough`  and it would not work in css, in css it should be named like `line-through`.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/111562742/224035247-cd24cfdb-34d6-410e-a6dd-aba73e3afb5c.png">

Tokens for letter spacing have values with `%` and they will not work properly in css as well:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/111562742/224035114-393674f7-8d23-4242-a991-75e648ed06e5.png">

**Expected behavior**
For the text decoration we have a value like `strikethrough`  and it should be replaced with `line-through`.

For the letter spacing proper values are like described here: https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing

**Comment by DanielleRameau** [comment]
will be solved in epic #1005
