### ISSUE TITLE
Generate themes as part of CI and do not commit those files

### ISSUE THREAD

**Issue by jpzwarte** [sl-design-system/components#425]
This improves the DX because changes to themes won't be part of commits and PRs. At the moment, some PRs contain more changes to themes than actual component changes.

- [ ] Remove generated theme files from git
- [ ] Add `build:themes` as part of the release build
- [ ] Add `build:themes` as part of the local `yarn start --watch` pipeline so you get to see changes to tokens reflected in the themes in Storybook
- [ ] Make sure the theme NPM packages contain the generated files

**Comment by DanielleRameau** [comment]
First step: Timebox 1 day: research + try: if it works, implement it :)
More than 1 day: wait until after releasing V1, put it on refining again, and document what you've done
