### ISSUE TITLE
Basic documentation of Radio

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#427]
```[tasklist]
### Tasks
- [x] UX documentation
- [x] technical documentation
- [x] accessibility documentation
- [ ] Launch on sanomalearning.design
- [ ] live example needs to be fixed
```

**Comment by Diaan** [comment]
https://confluence.sanomalearning.com/pages/viewpage.action?pageId=411581406

**Comment by Diaan** [comment]
Tried to make a component for the "install info" so we can reuse that everywhere, but with the simplest option the "code" functionality and styling (grey background, copy button etc) doesn't work anymore, so those need to be components as well.

Not 100% that is something that should be part of this story. Will discuss this during the standup tuesday. (or feel free to comment here if you read it 😀  )
