### ISSUE TITLE
Fix loading of styles in Angular Storybook

### ISSUE THREAD

**Issue by Diaan** [sl-design-system/components#434]
The angular part in storybook doesn't load the themes styles correctly

**Comment by anna-lach** [comment]
Partially added changes on branch: https://github.com/sl-design-system/components/tree/fix/434-fix-styles-in-angular-storybook

There is still a problem with applying styles in only one iframe (we have two iframes, one for storybook with web components and second one for Angular storybook).

**Comment by jpzwarte** [comment]
This is an issue with storybook itself: https://github.com/storybookjs/storybook/issues/15805

The workaround for now is that you have to refresh the page if you're on an Angular story. After the refresh, the theme is correct.
