### ISSUE TITLE
[V1] Card

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#525]
## User Story
As a Sanoma Learning Design System user, I want a versatile and user-friendly Card Component that can effectively handle various use cases across our educational products. This Card Component should be adaptable to convey:

## Definition
A card can be used to display content related to a single subject. The content can consist of multiple elements of varying types and sizes.

## Key Points
- Container for multiple types of contents.
- Provide two slots: One in the header and a body slot.

![Image](https://github.com/sl-design-system/components/assets/77982487/f67a4a79-d6b4-48c1-bf8a-feaddaaf8dfc)

## Acceptance Criteria

**Elements**
| Name  | Optional |
| ------------- | ------------- |
| Media | Yes |
| Title | No |
| Icon | Yes |
| Contextual Menu | Yes |
| Header Slot | Yes |
| Body Slot | Yes |

**Column Width** 
- Expanded (Mobile)
- Fixed

**Row Width** 
- Small
- Medium (Default)
- Large

**Padding**
- None
- Default

**A11y**
- Aria-Label of the card with the title???

## Figma Links
- [Figma Tabs Component Research](https://www.figma.com/file/PGb66fVN325tu0IngRka66/SL-Component-Research?type=design&node-id=340-1225&mode=design&t=LTtBS4hrwzAj5ixt-4)
- [Design] (https://www.figma.com/file/SKFTFiiz7YK9E2TPfCan9o/Base-Components?type=design&node-id=4865-3350&mode=design)

```[tasklist]
### User stories
- [ ] https://github.com/sl-design-system/components/issues/733
- [ ] https://github.com/sl-design-system/components/issues/628
- [ ] https://github.com/sl-design-system/components/issues/629
- [ ] https://github.com/sl-design-system/components/issues/630
```

**Comment by DanielleRameau** [comment]
Show icon only button when there is 1 action, show more button if there are 2 or more actions.

**Comment by Diaan** [comment]
Little request; please also think about/describe how the image grows/crops when the card is scaled; 
- Does the image maintain aspect ratio?
-- What happens when you have a landscape photo and a large body text? that will never fit. 
-- or does the media always cover the full height? If not, should it be positioned at the top, or center?

**Comment by Diaan** [comment]
> Show icon only button when there is 1 action, show more button if there are 2 or more actions.

Are there designs for this? Is it really MVP?
