### ISSUE TITLE
[V1] Tabs

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#527]
## User Story
As a Sanoma Learning Design System user, I want a versatile and user-friendly Tab Component that can effectively handle various use cases across our educational products. This Tab Component should be adaptable to convey:

## Definition
Tabs are used to organize related content. They allow the user to navigate between groups of information that appear within the same context.

## Key Points
- Clear Indication of Active Tab.
- Ensure that your tabs adapt well to different screen sizes.
- Maintain a standardised placement for tabs.
- Flexibility for Content Variation.
- Make sure that tab navigation is keyboard-friendly.

## Acceptance Criteria

**Elements**
| Name  | Optional |
| ------------- | ------------- |
| Label | No |
| Subtitle | Yes |
| Icon | Yes |
| Badge | Yes |

**States**
The status defines how the design system visually displays the components inside of the message. 
- Default
- Hover
- Active/Pressed
- Disabled

**Sizes** 
- Medium (Default)

**Layout**
- Horizontal (Default)
- Vertical

**Alignment**
- Left

**Width (tabs)**
- Hug Content 
- Fill Container

**Behaviour** 
- Sticky Tabs Header
- Overflowing tabs: show more tab + dropdown, (show all tabs in dropdown) + slide
Example: https://ant.design/components/tabs

**A11y**
- Navigation through content with the tab key.
- Move through the tabs with the arrow keys.
- Show up "Contextual Menu" (···) when the tabs overflow the width of the container.

## Figma Links
- [Figma Tabs Component Research](https://www.figma.com/file/PGb66fVN325tu0IngRka66/Component-Research?type=design&node-id=270-1340&mode=design&t=eQ4xHOVJ9nGgAcYR-4)

```[tasklist]
### User stories
- [ ] #139
- [ ] https://github.com/sl-design-system/components/issues/728
- [ ] https://github.com/sl-design-system/components/issues/729
- [ ] https://github.com/sl-design-system/components/issues/730
- [ ] https://github.com/sl-design-system/components/issues/731
- [ ] https://github.com/sl-design-system/components/issues/931
```

**Comment by anna-lach** [comment]
@arecuenco-dsgn it looks like this point from **a11y** part is not applicable:
`Shows up arrow tabs when the tabs are overflow the width of the container.`. We've chosen the version with dropdown showing all tabs.

**Comment by arecuenco-dsgn** [comment]
@anna-lach, I update it; what do you think? 
_"Show up "Contextual Menu" (···) when the tabs overflow the width of the container."_

**Comment by anna-lach** [comment]
Sticky tabs header should be optional (possible to add with styling), by default it'll not be sticky.
