### ISSUE TITLE
Write text for developer to go on the getting started page

### ISSUE THREAD

**Issue by Diaan** [sl-design-system/components#559]
After reading the getting started page a developer knows...
```[tasklist]
### Acceptance criteria
- [x] ... how get access to the SLDS NPM package
- [x] ... how to add the SLDS component library from NPM
- [x] ... how to load the correct theme into their application
- [x] ... how to use a component
- [x] ... where to find an example project so they have a real world example they can be inspired by (read: copy from)
```

**Comment by Diaan** [comment]
@DanielleRameau can we add links to storybook as well? Or is that not allowed because of the fact that the themes are not open source?

**Comment by DanielleRameau** [comment]
@Diaan I don't believe that's a problem because Storybook isn't password-protected, provided we refrain from marketing all the various themes.
