### ISSUE TITLE
Design getting started page

### ISSUE THREAD

**Issue by Diaan** [sl-design-system/components#560]
```[tasklist]
### Tasks
- [x] page design is based on current page layout
- [x] Light mode
- [x] all breakpoints
- [x] Side navigation jumpy thingy to navigate to designers and developers
```

Getting started designers: https://confluence.sanomalearning.com/pages/viewpage.action?pageId=411582265
Getting started developers: https://github.com/sl-design-system/components/blob/main/GETTING_STARTED.md

**Comment by DanielleRameau** [comment]
You can find the design here: https://www.figma.com/file/fpvv1aBzMNVTbJaFHhraB9/SL---Web-Generator?type=design&node-id=1712%3A4280&mode=design&t=J0LBxF4OKLtSwToV-1

For the side navigation you can use the sub menu we also use for the tokens. Switch between 'developers' and 'designers'

**Comment by DanielleRameau** [comment]
No need to implement the footer now.
