### ISSUE TITLE
Basic Documentation of Spinner

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#626]
```[tasklist]
### Tasks
- [ ] https://github.com/sl-design-system/components/issues/622
- [x] usage tab
- [x] code tab
- [x] a11y tab
```

**Comment by DanielleRameau** [comment]
@Diaan can you fill the code tab?

**Comment by Diaan** [comment]
- Aria on spinners/ skeletons?
    - Should we set anything on the component itself? 
        - role=“status”? Progress bar?
        - Aria-busy?
    - Add “aria-busy” on the container that is loading the stuff?
        - Or aria-live? But what if you have 5 lazy loaded area’s that all finish loading at different times? With live regions they will all notify the user, that is not what you want.

**Comment by Diaan** [comment]
aria-hidden and role-presentation on spinner.

Aira-busy on container only when result of user action, not on page load.
