### ISSUE TITLE
Use @property for tooltip offset

### ISSUE THREAD

**Issue by Diaan** [sl-design-system/components#656]
> Perhaps check if we can use `@property` with a fallback for FF/older browsers? https://caniuse.com/mdn-css_at-rules_property

_Originally posted by @jpzwarte in https://github.com/sl-design-system/components/pull/642#discussion_r1332650442_

**Comment by DanielleRameau** [comment]
@jpzwarte is this really important? Please have a look.

**Comment by jpzwarte** [comment]
@DanielleRameau yes, this issue is still relevant.

**Comment by jpzwarte** [comment]
With the refactor of tooltip in #984, this is no longer relevant.
