### ISSUE TITLE
Simplify working with forms

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#660]
# Simplify working with forms in Lit
## This feature is part of the milestone [link to feature]

Angular has support for forms using the `FormGroup` API. See https://angular.io/guide/forms-overview

In web component land, there is no such thing, only `<form>`. But `<form>` does not allow for such complex forms:
- It only supports strings
- It does not support sub-forms
- It does not cross the shadow DOM
- It only supports field validation, not form-level validation

When working with Lit, we need the ability to create complex forms. This may look similar to this:

```
form = new FormGroup(this, {
  input: new FormControl(this, '', [Validators.required])
});

<form @submit=${this.#onSubmit}>
  <sl-label for="input">Label</sl-label>
  <sl-text-input id="input" ${this.form.bind('input')}></sl-text-input>
</form>

#onSubmit(event) {
  event.preventDefault();

  if (this.form.reportValidity()) {
    const value = this.form.value;

    ...
  }
}
```

We don't need to reinvent the wheel here. For example, since all our form controls implement the HTML5 validation API, our form code can simply call `setCustomValidity` to set the validation message on the control.

Also, for sub-form web components, we can investigate whether we can use `ElementInternals` to have the sub-form integrate with the parent form.

| <div align="left">**What is the problem we are solving and why?**  |
| ------------- |
|As a user, I want to use complex forms, so I can get stuff done| 
|As a developer, I want easily create complex forms, so I can help users|

```[tasklist]
### User stories
- [ ] https://github.com/sl-design-system/components/issues/686
- [ ] https://github.com/sl-design-system/components/issues/725
```

**Comment by jpzwarte** [comment]
This was completed in #752
