### ISSUE TITLE
Button: solid button lacks border

### ISSUE THREAD

**Issue by jpzwarte** [sl-design-system/components#666]
**Describe the bug**
A medium solid button has only 28px height, while the medium outline button has 32px height. 

**To Reproduce**
1. Go to ['...'](https://kind-plant-088739303.1.azurestaticapps.net/?path=/story/button--all&globals=theme:magister)
2. Inspect the medium solid button

**Expected behavior**
They should have the same height.

**Screenshots**
![CleanShot 2023-09-26 at 10 36 12@2x](https://github.com/sl-design-system/components/assets/3968/d54d1cc1-fbd1-4c69-9191-e60fb4048382)
![CleanShot 2023-09-26 at 10 36 40@2x](https://github.com/sl-design-system/components/assets/3968/e98bc1dc-3c01-4590-bf9f-5b1dae95ec07)

**Comment by Diaan** [comment]
The issue is because the border width properties are still using the old name "default" instead of "solid".
This is actually the case for all themes. We can't fix this in code without creating an unmaintainable mess.

**Comment by DanielleRameau** [comment]
Daantje fixed it!!!
