### ISSUE TITLE
UX research + wireframe accordion

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#743]
```[tasklist]
### Tasks
- [x] What do we have right now?
- [x] Ux research: best practices
- [x] Create wireframe
- [x] Acceptance criteria
```

**Comment by DanielleRameau** [comment]
Check article of NN group

**Comment by Diaan** [comment]
I miss the description of how its going to work; 
- Is it possible to open multiple panels at the same time? Or should this be an option, and if so, what is the default value?
- Scroll into view; when you open a panel; should the entire panel scroll into view? Or scroll the header to the top of the page? Or should scrolling only happen when on opening one panel another one closes that causes the one you just opened to be out of view?
- With regards to a11y it just says "keyboard navigation", how should this work? 
-- tab to "enter" the component, then use arrow keys, like in checkbox groups, enter or space to open/close the panel, 
-- when a panel is opened you can use tab to focus things in the panel.
- I don't see any of the things we added in the "Behaviour" column during our session addressed in the acceptance criteria...

- In the panel in figma there is also a card about tabs, and in one card it mentions the spinner
