### ISSUE TITLE
Improve getting started documentation for developers

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#745]
As a developer I want to see a list of steps I need to take in order to get the SLDS working with my theme.
- GitHub token setup so you can `npm add` the NPM packages
- What to do to get the SLDS colors & fonts of my CFA to work
- What to do to get a simple `<sl-button>` to show up in my web application (Angular?)

Clear steps on what you need to add to `.npmrc` or `.yarnrc.yml`:
```
@sl-design-system:registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken=XXXXXXXXX
```
(in the case of `.npmrc`)

```[tasklist]
### User stories
- [x] Angular + Svelte documentation
- [x] What do I need to do to let it work in my angular application?
- [x] Add clear steps on getting started page (step 1,2,3)
- [x] Why is my font not showing up?
- [x] Mention SSR
- [x] Mention how to switch between light and dark (is dark mode is available)
- [x] How to create a GitHub Token: should be classic & should have `read_packages` privilege at least
- [x] How to use the shared token within Bitbucket Pipelines
- [x] What Angular versions we support
```

![CleanShot 2023-11-15 at 11 54 42@2x](https://github.com/sl-design-system/components/assets/3968/1f772180-a41e-4243-bc44-f7b2b3566c8a)

**Comment by anna-lach** [comment]
Maybe also make some research about preparing bundle for Angular of our npm packages?

**Comment by Diaan** [comment]
https://sanoma-my.sharepoint.com/:w:/p/diana_broeders/ETWhVQXL_zNEsDyvMkg1U0YBErW7p4ww-NPFo5K8onxMfg?e=mJDQJi
The current how to annotated with changes
