### ISSUE TITLE
Process for adding issues in GitHub

### ISSUE THREAD

**Issue by Diaan** [sl-design-system/components#765]
**Process for adding issues in GitHub**
Inspired by _What is the process of MVP release in details? The process for adding issues by dev teams etc.?_ in _Longed for_
Sprint 17 retrospective
https://secure.teamretro.com/meetings/056KBKJgRcgSJzVjoPSMjq?actionId=4eSjjTxZZDMRVCE4dvhlXj

**Comment by Diaan** [comment]
also have a look at the templates, both for adding a bug and for adding a feature request (the latter should be focussed on the problem rather than the solution)

**Comment by DanielleRameau** [comment]
is part of new roadmap, will place this user story in the new epic
