### ISSUE TITLE
Checkbox: Label is not read using Voice Over in Safari

### ISSUE THREAD

**Issue by furstenberg** [sl-design-system/components#789]
**Describe the bug**

When navigating the checkbox page at https://sanomalearning.design/categories/components/checkbox/ I'm not able to hear the label of the checkboxes.

**To Reproduce**

1. Open Safari.
2. Go to https://sanomalearning.design/categories/components/checkbox/
3. Start Voice Over (if not running already)
4. Use Tab to navigate to the Checkbox group (a skip link at the top of the page would be nice :-) )
5. Notice that as you navigate within the checkboxes using arrow keys, it does not read the label.

**Expected behavior**

I expect to hear the label.

**Screenshots**

<img width="813" alt="checkbox-label" src="https://github.com/sl-design-system/components/assets/18802/c1c5feeb-8316-4311-93f0-e7c6b02fa2ce">

**Desktop (please complete the following information):**
 - OS: [macOS 13.6.1]
 - Browser [Safari 17.1.2]
```[tasklist]
### Tasks
- [ ] try to reproduce it
```

**Comment by furstenberg** [comment]
It _is_ read in Chomium and Firefox using Voice Over on the same example.

**Comment by furstenberg** [comment]
And testing the checkbox at https://kind-plant-088739303.1.azurestaticapps.net/?path=/story/checkbox--api&globals=theme:itslearning, the visual label is not read, but there is another label (using aria-label I take it) that is being read.

So it's just the example on the [documentation page](https://sanomalearning.design/categories/components/checkbox/) that fails for me in Safari.

**Comment by anna-lach** [comment]
@furstenberg we've made some changes to the `sl-checkbox` and `sl-checkbox group`. Can you please take a look at the version we currently have in storybook https://storybook.sanomalearning.design/?path=/story/form-checkbox--basic and on the website https://sanomalearning.design/categories/components/checkbox/usage/ and let us know if you can still reproduce the bug?

**Comment by furstenberg** [comment]
The label is now indeed read. So the issue I reported appears to be fixed. :-)

I did notice another issue though. The state of the checkbox is not read. 

Using Voice Over in Safari, you can see in these videos that all checkboxes are reported as "unticked" even though some of them are "ticked". Voice Over uses "ticket" and "unticked" where other screen readers might use "checked" and "unchecked".

https://github.com/sl-design-system/components/assets/18802/633c50a1-b5af-4cea-95a5-562149af2929


https://github.com/sl-design-system/components/assets/18802/7eaa7142-5924-4793-a105-7292e20fa654

**Comment by anna-lach** [comment]
@furstenberg We've added another changes to the `sl-checkbox` component, can you please take a look once again? 
In storybook: https://kind-plant-088739303-1330.westeurope.1.azurestaticapps.net/?path=/story/getting-started-checklist--basic and on the website: https://proud-water-0d02ee203-1330.westeurope.2.azurestaticapps.net/
The problem with not read checkbox state in Safari should be fixed.

**Comment by furstenberg** [comment]
Hi.

The checkbox now works as expected in Safari using Voice Over. :-)
