### ISSUE TITLE
Background SL button

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#798]
Provide consistency in background of outline button within in all themes.

```[tasklist]
### Tasks
- [x] outline button should be transparent
- [x] check and fix outline button in all themes
- [x] double check
```

**Comment by DanielleRameau** [comment]
see branch #797

**Comment by Diaan** [comment]
There is no consistency between and an IN themes in what the outline button looks like with regards to the background color. I made these screenshots in the LIGHT theme, but made the background black so you can see the background-colour of the button.
Max:
<img width="250" alt="image" src="https://github.com/sl-design-system/components/assets/1351956/b7133560-7b64-4e85-988c-73026dd7751e">
Bingel:
<img width="389" alt="image" src="https://github.com/sl-design-system/components/assets/1351956/31c00ac9-dee4-4efd-a5cb-5332c48410e6">
clickedu:
<img width="362" alt="image" src="https://github.com/sl-design-system/components/assets/1351956/b8e21959-a1d3-48b9-873e-29f90cbed99e">
Kampus:
<img width="390" alt="image" src="https://github.com/sl-design-system/components/assets/1351956/84089bb9-b79d-458d-9d21-e07c6d573073">
My Vanin:
<img width="372" alt="image" src="https://github.com/sl-design-system/components/assets/1351956/ac481101-f195-4864-9acb-b843198f3d39">
Neon/Nowa Era:
<img width="401" alt="image" src="https://github.com/sl-design-system/components/assets/1351956/fb65d04f-cd5b-4c6a-8b01-20ddcba84fce">
Sanoma Learning (these are the solid buttons, not the outline):
<img width="433" alt="image" src="https://github.com/sl-design-system/components/assets/1351956/af012dd4-f1ae-4160-9409-8dc05e5ed36b">
