### ISSUE TITLE
$0.disabled is undefined

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#808]
Hello I am Oscar Ledesma from Bingel team pokemon and we were using sl-button with disabled attribute, it disables nicely but when we try to test it with $0 through the console in chrome it says $0.disabled is undefined.

![Image](https://github.com/sl-design-system/components/assets/111998351/1963f3f2-9134-477f-bca0-111dc79740eb)

**Comment by jpzwarte** [comment]
This is more of a question. `$0.disabled` being undefined is by design. I've answered Oscard on Slack.
