### ISSUE TITLE
Problems with rendering icons

### ISSUE THREAD

**Issue by anna-lach** [sl-design-system/components#824]
There is sometimes a problem when loading icons. 
For example in inline-message component when the component is loaded for the first time (check in storybook) there is no icon rendered and only when I refresh or go to another inline message story I can finally see the icon.

**Screenshots**
![image](https://github.com/sl-design-system/components/assets/111562742/18022b89-458c-4ce0-8f17-0c878441a138)

![image (1)](https://github.com/sl-design-system/components/assets/111562742/e6d9c684-3981-46e4-b680-702e1ae81b67)

**Comment by anna-lach** [comment]
The problem was also heard by @jpzwarte from other people.

**Comment by Diaan** [comment]
Fixed in duplicate story: #830
