### ISSUE TITLE
Improve generating properties using custom elements manifest

### ISSUE THREAD

**Issue by anna-lach** [sl-design-system/components#832]
There is an improvement needed with generating component's properties. For now there is a problem with generating types, we need to use a kind of workaround like:

```
/** Skeleton's effect.
   *  @type {'none' | 'shimmer' | 'pulse' | 'sheen'}
   * */
  @property({ reflect: true }) effect: SkeletonEffect = 'shimmer';
  ```
  for type 
  `export type SkeletonEffect = 'none' | 'shimmer' | 'pulse' | 'sheen';`
  
  Maybe the solution can be using this plugin: https://www.npmjs.com/package/cem-plugin-expanded-types
  
  Please check if this not breaks what we have now in the documentation website.

**Comment by Diaan** [comment]
There is an issue with optional properties that have types that are defined outside that file. Issue is mentioned to the maintainer(s): https://github.com/break-stuff/cem-tools/issues/18
