### ISSUE TITLE
Fix NPM theme packages

### ISSUE THREAD

**Issue by jpzwarte** [sl-design-system/components#914]
- Even if a theme does not have a dark mode, we still generate `all.css` with media queries for light & dark mode. Using `all.css` will break your web app when the OS is in dark mode
- We name files `base.css` and `base.scss` which can be difficult with tooling. Some tooling may always prefer the `.scss` file extension even though the developer wants it to include the `.css` extension
- The files contain the tokens for *all* components; if you are only using 1 component, then a lot is unnecessary bloat. 

Solutions:
1. Check if there is a dark mode and if not, output the light tokens *without* a media query in `all.css`
2. Put the `*.scss` files in a `mixins` folder so there can be no confusion.
3. Consider splitting the tokens into different files (1 for each component?)

**Comment by DanielleRameau** [comment]
@jpzwarte can you do an estimation fo this one? Diana thinks a 2, but isn't sure, please help us out :)
